### PR TITLE
Major Changes

### PR DESCRIPTION
**Pull request by TheInsanec0der**
- Added Partners Page
- Added privacy policy page
- Changed Lunatic & Poison's avatar in staff section (*because they changed it again*)

### CODE REVIEW

**Comment by SidisLiveYT** [comment]
partner Area looks great But Ponbus Image isn't loading and can you resolve index.html , Can you change background with a gif ? May look cool

**Comment by TheInsanec0der** [comment]
I've fixed the issue with Ponbus' logo. Also which GIF do you want to be in the bg?

**Comment by SidisLiveYT** [comment]
> I've fixed the issue with Ponbus' logo. Also which GIF do you want to be in the bg?

Thanks man!! Regarding Gif You can choose any , some Relaxing and related to Anime Stuff . Not aggressive or bloddy thing as Jericho meant for non-NSFW Stuff and friendly bot

**Review by SidisLiveYT — CHANGES_REQUESTED** [review]
I guess index.html needs to resolved for merge , and btw background seems very distorted

**Pull request closed without merging**
